name: Lint, Build & Test workflow

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run Code Lint
        run: |
          yarn prettier
          yarn lint

      - name: Run Test with Coverage
        run: yarn coverage

      - name: Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Run Build
        run: yarn build
